/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testAndChallenges;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testInsertShiftArray(){

        ArrayShift test = new ArrayShift();
        int[] arr = {1,2,3,4,5};
        int elem = 11 ;
        int[] newArray = test.insertShiftArray(arr,elem);
        int[] expectedArray = {1,2,3,11,4,5};
        assertArrayEquals("should return 1,2,3,11,4,5",expectedArray,newArray);


        //test2 if the array is empty
        int[]arr2={};
        elem = 7;
        int[]expected2={7};
        int[] newArray2 = test.insertShiftArray(arr2,elem);
        assertArrayEquals("should return 7",expected2,newArray2);


    }
}
