/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utilities;

import org.checkerframework.checker.units.qual.C;

public class App {

    public static void main(String[] args) {
        AnimalShelter animalShelter = new AnimalShelter();

        Dog d1 = new Dog("dog number 1");
        Dog d2 = new Dog("dog number 2");
        Dog d3 = new Dog("dog number 3");
        Cat c1 = new Cat("cat number 1");
        Cat c2 = new Cat("cat number 2");
        Cat c3 = new Cat("cat number 3");

        animalShelter.enqueue(d1);
        animalShelter.enqueue(d2);
        animalShelter.enqueue(c1);
        animalShelter.enqueue(c2);
        animalShelter.enqueue(d3);
        animalShelter.enqueue(c3);


        System.out.println(animalShelter.getSize());
        System.out.println(animalShelter.dequeue("dog"));
        System.out.println(animalShelter.dequeue("dog"));


    }
}
