/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)
    {

        QuickSort quickSort = new QuickSort();

        int[] arr = {8,4,23,42,16,15};
        int[] sorted = quickSort.sort(arr);

        System.out.println(Arrays.toString(sorted));


    }
}
