/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    LinkedList testList = new LinkedList();
    @Test public void testEmptyLinkedList(){
        String output = testList.toString();
        assertEquals("Must be NULL", "NULL",output);
    }
    @Test public void testInsertToList(){
        testList.insert(7);
        String output = testList.toString();
        assertEquals("Must be { 7 } --> Null", " { 7 } --> NULL",output);
    }
    @Test public void testHeadValue(){
        testList.insert(7);
        int output = testList.head.value;
        assertEquals("Must be 7", 7,output);
    }
    @Test public void testInsertMultipleToList(){
        testList.insert(7);
        testList.insert(6);
        testList.insert(5);
        testList.insert(4);
        String output = testList.toString();
        String expected = " { 4 } -->  { 5 } -->  { 6 } -->  { 7 } --> NULL";
        assertEquals("Must be  { 4 } -->  { 5 } -->  { 6 } -->  { 7 } --> NULL", expected,output);
    }
    @Test public void testIncludeExistValue(){
        testList.insert(7);
        testList.insert(8);
        testList.insert(9);
        boolean isFound = testList.includes(8);
        assertTrue("Must be true",isFound);
    }
    @Test public void testIncludeNonExistValue(){
        testList.insert(7);
        testList.insert(8);
        testList.insert(9);
        boolean isFound = testList.includes(22);
        assertFalse("Must be true",isFound);
    }



}
