/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binarySearch;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void testBinarySearchMethod(){
        BinarySearch binary = new BinarySearch();
        int[] arr ={1,3,5,6,8,9,10};
        int index = binary.binarySearch(arr,6);
        int index2 = binary.binarySearch(arr,10);
        int index3 = binary.binarySearch(arr,5);
        int index4 = binary.binarySearch(arr,22);

        assertEquals("must be 3",3,index);
        assertEquals("must be 6",6,index2);
        assertEquals("must be 2",2,index3);
        assertEquals("must be -1",-1,index4);
    }
}
