/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.LinkedList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Graph <String> graph1 = new Graph();

        graph1.addNode("A");
        graph1.addNode("B");
        graph1.addNode("C");
        graph1.addNode("D");
        graph1.addNode("E");
        graph1.addNode("F");
        graph1.addNode("G");
        graph1.addNode("H");



        try {
            graph1.addEdge("A","B",0);
            graph1.addEdge("A","D",0);
            graph1.addEdge("B","C",0);
            graph1.addEdge("B","D",0);

            graph1.addEdge("C","G",0);
            graph1.addEdge("D","E",0);
            graph1.addEdge("D","H",0);

            graph1.addEdge("D","F",0);
            graph1.addEdge("F","H",0);



//            String[] nodes = {"Narnia", "Arendelle", "Naboo"};
//            String output = graph1.getEdges(nodes);
//            System.out.println(output);
            List<String> bft = graph1.BFT("A");
            List<String> dft = graph1.DFT("A");
            System.out.println(bft);
            System.out.println(dft);

        }
        catch(NodeNotFoundException ex){
            System.out.println(ex.getMessage());
        }



//        System.out.println(graph1);
//        System.out.println(graph1.getSize());
//        System.out.println(graph1.getNodes());


    }
}
