/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leftJoin;

import hashtable.Hashtable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Hashtable hash1 = new Hashtable();
        Hashtable hash2 = new Hashtable();

        hash1.add("found","enamored");
        hash1.add("wrath","anger");
        hash1.add("diligent","employed");
        hash1.add("outift","guard");
        hash1.add("guide","usher");


            char c = ':';
            Character.toLowerCase(c);

            int asci = c - 97;
            if( asci >= 0 && asci < 26)
                System.out.println(c);

        hash2.add("found","averse");
        hash2.add("wrath","delight");
        hash2.add("diligent","idle");
        hash2.add("flow","jam");
        hash2.add("guide","follow");

//        System.out.println(hash1.leftJoin(hash2));
    }
}
