/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {


    public static void main(String[] args) {

        LinkedList myList = new LinkedList();
        LinkedList myList2 = new LinkedList();

        myList.append(10);




        myList2.append(14);
        myList2.append(7);
        myList2.append(22);

        LinkedList newList = LinkedList.zipLists(myList,myList2) ;
        System.out.println(myList.toString());
        System.out.println(myList2.toString());
        System.out.println(newList);
        System.out.println(myList.isPalindrome());



    }
}
