/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {


    public static void main(String[] args) {

        LinkedList myList = new LinkedList();

        myList.insert(10);
        myList.insert(9);
        myList.insert(8);
        myList.insert(7);
        myList.insert(6);
        myList.insert(5);
//        myList.append(11);
//        myList.append(12);
//        myList.append(13);
//        myList.append(9);
        myList.insertBefore(10,2);
        myList.insertAfter(10,5);
        System.out.println(myList.toString());
        System.out.println(myList.includes(9));


    }
}
